version: '2'
services:

  #############
  # Jenkins
  #############
  jenkins:
    build: ./
    ports:
      - "8080:8080"
    environment:
      - JENKINS_USER=admin
      - JENKINS_PASS=admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #Enable to use docker in docker container
#    links:
#      - sonarqube
#      - artifactory


#  sonarqube:
#    image: sonarqube:alpine
#    ports:
#      - "9000:9000"
#      - "9092:9092"
#
#  artifactory:
#    image: docker.bintray.io/jfrog/artifactory-oss:5.11.0
#    container_name: artifactory
#    ports:
#     - 8081:8081


