spring:
  data:
    neo4j:
      uri: bolt://localhost
      username: neo4j
      password: secret
  kafka:
    bootstrap-servers: 0.0.0.0:9092
      

management:
   endpoints:
      enabled-by-default: true
      web:
         exposure:
            include: '*'

app:
  topic: feed-item-complete      
  
  