spring:
  data:
    neo4j:
      uri: bolt://localhost
      username: neo4j
      password: secret
      
spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  topic: feed-item-extracted      