apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: search-api
  name: search-api
  namespace: devbunch
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: search-api
    weight: 100
  wildcardPolicy: None
