version: '2'
services:

  #############
  # PostgreSQL
  #############
  postgres:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=devbunch_db
    networks:
      - postgres
    volumes:
      - /usr/share/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    links:
      - postgres:postgres
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
     - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - postgres
    restart: unless-stopped

  #############
  # ELK
  #############
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.4
    container_name: elasticsearch
    environment:
      - node.name=devbunch-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.4
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch

  #############
  # Kafka
  #############
  kafka-stack:
    # This will serve as our Kafka stack
    image: landoop/fast-data-dev:1.1.0
    environment:
      - FORWARDLOGS=0
      - RUNTESTS=0
    ports:
      - 3030:3030
    networks:
      - elk  

networks:
  postgres:
    driver: bridge
  elk:
    driver: bridge

volumes:
  elastic-data:
