spring.kafka:
  bootstrap-servers: 0.0.0.0:9092
  producer:
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true    
    
feed-collector:
  sender:
    topicName: feed-item