spring.kafka:
  bootstrap-servers: apache-kafka:9092
  producer:
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true    
  batch.job.enabled: false 
  
management:
   endpoints:
      enabled-by-default: true
      web:
         exposure:
            include: '*'  
    
feed-collector:
  cron: 0 0/15 * * * ?
  sender:
    topicName: feed-item
