apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: devbunch
spec:
  ports:
    - name: 9200-tpc
      port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    deploymentconfig: elasticsearch
  sessionAffinity: None
  type: ClusterIP
