apiVersion: v1
kind: Service
metadata:
  labels:
    app: graph-model
  name: graph-model
  namespace: devbunch
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: graph-model
  sessionAffinity: None
  type: ClusterIP
