apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: devbunch
spec:
  ports:
    - name: 7687-tpc
      port: 7687
      protocol: TCP
      targetPort: 7687
  selector:
    deploymentconfig: neo4j
  sessionAffinity: None
  type: ClusterIP
