apiVersion: v1
kind: Service
metadata:
  labels:
    app: search-api
  name: search-api
  namespace: devbunch
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: search-api
  sessionAffinity: None
  type: ClusterIP
