apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: graph-model
  name: graph-model
  namespace: devbunch
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'graph-model:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: develop
      uri: 'https://github.com/david-romero/devbunch.git'
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: MAVEN_ARGS_APPEND
          value: '-pl graph-model --also-make'
        - name: ARTIFACT_DIR
          value: graph-model/target/
        - name: MODULE_DIR
          value: graph-model
      from:
        kind: ImageStreamTag
        name: 'fuse-java:latest'
        namespace: devbunch
    type: Source
  triggers:
    - type: ConfigChange
