spring.kafka:
  bootstrap-servers: 0.0.0.0:9092

spring.jackson:
  serialization.write-dates-as-timestamps: true 
  
  
  
management:
   endpoints:
      enabled-by-default: true
      web:
         exposure:
            include: '*'
  
spring:
  datasource:
    initialization-mode: always