spring.kafka:
  bootstrap-servers: apache-kafka:9092

spring.jackson:
  serialization.write-dates-as-timestamps: true
  
  
management:
   endpoints:
      enabled-by-default: true
      web:
         exposure:
            include: '*' 
  
spring:
  datasource:
    initialization-mode: always